#!/usr/bin/env python3
"""Measure one /groom run and write <run folder>/run-metrics.md for the retro agent.

Usage:
  run_metrics.py <run folder>                 write run-metrics.md, e.g. groomed/<slug>/run-2_2026-09-27
  run_metrics.py <run folder> --tier          print the size tier (small | standard) from requirement.md
  run_metrics.py <run folder> --check <file>  print one file's size against its budget (for stage summaries)

Counts only; no judgement. The retro agent interprets the numbers. Budgets mirror CLAUDE.md and the
agent definitions; if you change a budget there, change it here too.
"""
import glob
import json
import os
import re
import sys
from collections import Counter

SMALL_MAX_WORDS = 200  # requirement word count at or below which a run is tier "small"

# Per tier: (file, low, high) in lines; None = no stated bound. Mirrors the table in CLAUDE.md.
BUDGETS = {
    "small": {
        "lines": [("prd-draft.md", None, 120), ("final-prd.md", None, 200), ("business-case.md", None, 15),
                  ("user-stories.md", None, 120), ("story-map.md", None, 20), ("definition-of-done.md", None, None),
                  ("coverage-report.md", None, None)],
        "stories": (3, 6), "scenarios": (2, 4), "dod": (5, 10), "rounds": 2,
    },
    "standard": {
        "lines": [("prd-draft.md", None, 250), ("final-prd.md", None, 400), ("business-case.md", None, 30),
                  ("user-stories.md", None, 220), ("story-map.md", None, 40), ("definition-of-done.md", None, None),
                  ("coverage-report.md", None, None)],
        "stories": (5, 10), "scenarios": (2, 5), "dod": (8, 15), "rounds": 3,
    },
}

ROW = re.compile(r"^\|\s*(DL-\d{3,})\s*\|")
CELL_SEP = re.compile(r"(?<!\\)\|")


def lines(path):
    try:
        with open(path, encoding="utf-8") as f:
            return f.read().splitlines()
    except FileNotFoundError:
        return None


def flag(n, lo, hi):
    if n is None:
        return "missing"
    if hi is not None and n > hi:
        return f"OVER (max {hi})"
    if lo is not None and n < lo:
        return f"under (min {lo})"
    return "ok" if (lo, hi) != (None, None) else "no budget"


def req_words(W):
    req = lines(os.path.join(W, "requirement.md")) or []
    return sum(len(l.split()) for l in req if not l.startswith("> Source:"))


def tier_of(W):
    """The tier recorded in run-state.json for this run, else computed from the requirement."""
    D = os.path.dirname(W.rstrip("/"))
    try:
        with open(os.path.join(D, ".state", "run-state.json"), encoding="utf-8") as f:
            for r in json.load(f).get("runs", []):
                if r.get("folder", "").rstrip("/") == W.rstrip("/") and r.get("size"):
                    return r["size"]
    except (FileNotFoundError, json.JSONDecodeError):
        pass
    return "small" if req_words(W) <= SMALL_MAX_WORDS else "standard"


def log_rows(path):
    rows = []
    for line in lines(path) or []:
        if ROW.match(line):
            cells = [c.strip() for c in CELL_SEP.split(line.strip())[1:-1]]
            if len(cells) == 6:
                rows.append(dict(zip(("id", "issue", "raised", "status", "resolution", "updated"), cells)))
    return rows


def main():
    if len(sys.argv) < 2 or not os.path.isdir(sys.argv[1]):
        sys.exit("usage: run_metrics.py <run folder> [--tier | --check <file>]")
    W = sys.argv[1].rstrip("/")
    if sys.argv[2:3] == ["--tier"]:
        print("small" if req_words(W) <= SMALL_MAX_WORDS else "standard")
        return
    tier = tier_of(W)
    B = BUDGETS[tier]
    LINE_BUDGETS, STORIES, SCENARIOS_PER_STORY, DOD_ITEMS, MAX_ROUNDS = (
        B["lines"], B["stories"], B["scenarios"], B["dod"], B["rounds"])
    if sys.argv[2:3] == ["--check"] and len(sys.argv) == 4:
        name = os.path.basename(sys.argv[3])
        lo, hi = next(((l, h) for n, l, h in LINE_BUDGETS if n == name), (None, None))
        ls = lines(os.path.join(W, name))
        n = None if ls is None else len(ls)
        print(f"{name}: {'missing' if n is None else f'{n} lines'} · budget ({tier}): "
              f"{'≤ ' + str(hi) if hi else 'none'} · {flag(n, lo, hi)}")
        return
    D = os.path.dirname(W)
    m = re.match(r"run-(\d+)_", os.path.basename(W))
    if not m:
        sys.exit(f"not a run folder: {W}")
    k = m.group(1)
    tag = f"run{k}-"
    out = [f"# Run metrics — {os.path.basename(D)} run {k} (size tier: {tier})", "",
           "_Generated by scripts/run_metrics.py. Counts only; interpretation is the retro's job._", ""]

    # Size
    req = lines(os.path.join(W, "requirement.md")) or []
    req_n = max(len([l for l in req if l.strip() and not l.startswith("> Source:")]), 1)
    out += ["## Size", "| File | Lines | Budget |", "|---|---|---|",
            f"| requirement.md (non-empty, excl. source line) | {req_n} ({req_words(W)} words) | — |"]
    total = 0
    for name, lo, hi in LINE_BUDGETS:
        ls = lines(os.path.join(W, name))
        n = None if ls is None else len(ls)
        total += n or 0
        out.append(f"| {name} | {'—' if n is None else n} | {flag(n, lo, hi)} |")
    rounds_lines = sum(len(lines(p) or []) for p in glob.glob(os.path.join(W, "rounds", "*.md")))
    out += [f"| rounds/*.md (all) | {rounds_lines} | — |", "",
            f"Growth: {total} lines of deliverables from {req_n} requirement lines (×{total / req_n:.0f}).", ""]

    # Stories
    us = lines(os.path.join(W, "user-stories.md")) or []
    per_story, current = Counter(), None
    for l in us:
        h = re.match(r"^#{2,4}\s*(US-\d+)", l)
        if h:
            current = h.group(1)
        elif re.match(r"^#{1,2}\s", l):
            current = None
        if current and "Scenario" in l and re.search(r"Scenario( Outline)?:", l):
            per_story[current] += 1
    stories = sorted({re.match(r"^#{2,4}\s*(US-\d+)", l).group(1) for l in us if re.match(r"^#{2,4}\s*US-\d+", l)})
    out += ["## Stories", f"- Stories: {len(stories)} ({flag(len(stories), *STORIES)})",
            f"- Scenarios: {sum(per_story.values())}"]
    bad = [f"{s}={per_story[s]}" for s in stories if flag(per_story[s], *SCENARIOS_PER_STORY) != "ok"]
    out.append(f"- Stories outside {SCENARIOS_PER_STORY[0]}–{SCENARIOS_PER_STORY[1]} scenarios: "
               f"{', '.join(bad) or 'none'}")
    dod = lines(os.path.join(W, "definition-of-done.md")) or []
    dod_ids = {x for l in dod for x in re.findall(r"\*\*(DoD-\d+)\*\*", l)}
    out += [f"- Definition of Done items: {len(dod_ids)} ({flag(len(dod_ids), *DOD_ITEMS)})", ""]

    # Debate
    out += ["## Debate", "| Round | Verdict | NEW_ISSUES | BLOCKING |", "|---|---|---|---|"]
    for p in sorted(glob.glob(os.path.join(W, "rounds", "r*-analyst.md"))):
        text = "\n".join(lines(p) or [])
        get = lambda key: (re.search(rf"^{key}:\s*(.+)$", text, re.M) or [None, "—"])[1].strip()
        rnd = re.match(r"r(\w+)-analyst", os.path.basename(p)).group(1)
        out.append(f"| {rnd} | {get('VERDICT')} | {get('NEW_ISSUES')} | {get('BLOCKING')} |")
    out.append("")

    # Decision log
    rows = log_rows(os.path.join(D, "decision-log.md"))
    mine = [r for r in rows if r["raised"].startswith(tag)]
    by_round = Counter(r["raised"][len(tag):] for r in mine)
    touched = [r for r in rows if tag in r["resolution"] or r["updated"].startswith(tag)]
    count = lambda s: sum(1 for r in touched if s in r["resolution"])
    out += ["## Decision log",
            f"- Rows in log: {len(rows)} · raised this run: {len(mine)} "
            f"({', '.join(f'{k2}: {v}' for k2, v in sorted(by_round.items()))})",
            f"- Status now: {', '.join(f'{s}: {n}' for s, n in Counter(r['status'] for r in rows).most_common())}",
            f"- Resolved as — FIX: {count('FIX:')} · ACCEPTED RISK: {count('ACCEPTED RISK')} · "
            f"PO DECISION: {count('PO DECISION')} · TECH QUESTION: {count('TECH QUESTION')}",
            f"- REOPENED: {count('REOPENED')} · NOT ADDRESSED: {count('NOT ADDRESSED')} · "
            f"COVERAGE GAP: {count('COVERAGE GAP')} · deferred to grooming: {count('deferred to grooming')}", ""]

    # PO interaction
    facts = lines(os.path.join(D, "confirmed-facts.md")) or []
    this_run = [l for l in facts if f"/groom run {k}," in l]
    out += ["## Product owner",
            f"- Facts confirmed this run: {len(this_run)} "
            f"(PO decisions on DL rows: {sum(1 for l in this_run if 'PO decision on DL-' in l)})", ""]

    # Run state
    try:
        with open(os.path.join(D, ".state", "run-state.json"), encoding="utf-8") as f:
            run = next((r for r in json.load(f).get("runs", []) if str(r.get("run")) == k), {})
    except (FileNotFoundError, json.JSONDecodeError):
        run = {}
    out += ["## Run", f"- Rounds: {run.get('rounds', '—')} of {MAX_ROUNDS} · final verdict: {run.get('verdict', '—')}",
            f"- Started: {run.get('started', '—')} · completed: {run.get('completed', '—')}", ""]

    dest = os.path.join(W, "run-metrics.md")
    with open(dest, "w", encoding="utf-8") as f:
        f.write("\n".join(out))
    print(f"wrote {dest}")


if __name__ == "__main__":
    main()
